{{ if .Values.bundle.enabled }}
{{- $this := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}-bundle-configmap
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $path, $_ :=  .Files.Glob  .Values.bundle.path }}
  {{ $path | replace "/" "-" }}: |-
  {{ base $path }}: |-
{{ tpl ($this.Files.Get $path) $this | indent 4 }}
  {{- end }}
{{ end }}
