apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}-configmap
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
